name: label_scanner
description: In-store label processing app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera functionality
  camera: ^0.10.6
  permission_handler: ^11.3.1
  
  # Sensors for QA features
  sensors_plus: ^5.0.1
  
  # Location services
  geolocator: ^10.1.0
  location: ^5.0.3
  
  # Storage and file handling
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Upload Queue System - CRITICAL NEW DEPENDENCIES
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  battery_plus: ^6.0.2
  flutter_image_compress: ^2.3.0
  package_info_plus: ^8.0.2
  uuid: ^4.5.1
  crypto: ^3.0.5
  dio: ^5.7.0
  
  # Essential dependencies
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/images/store_logos/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/instore_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/instore_logo.png"
